---
title: "PEO ACWA Performance Management"
date: "`r Sys.Date()`"
output: pdf_document
geometry: margin=0.05in
params:
  HQ_FY: NA
  PB_FY: NA
  BG_FY: NA
  feedback: NA
  cwd: NA
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{color}
  - \usepackage{multirow}
  - \usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
documentclass: article
classoption: a4paper
---

```{r,echo=FALSE}
source(paste(params$cwd,'R/data_prep.R',sep = "/"))
#  - \usepackage[table]{xcolor}
#  - \usepackage[dvipsnames]{xcolor}
```

```{r,echo=FALSE}

options(knitr.table.format = "latex")
library(dplyr)
library(kableExtra)
library(formattable)
df.hq <- params$HQ_FY
df.pb <- params$PB_FY
df.bg <- params$BG_FY
df.feedback <- params$feedback


makePretty <- function(df,site.name,bkcolor){
  title.array <- c(10)
  names(title.array) <- c(site.name)
  tmp <- kable(df,format = "latex",col.names = c(rep(c("Metric","Actual"),5)),align = 'c') %>% 
  kable_styling(latex_options = "striped", full_width = F, font_size = 8) %>%
  column_spec(0:1, bold = T,width="19em") %>%
  column_spec(2:10,width="1cm") %>%
  add_header_above(c("Outreach Event or Distribution ", "Q1" = 2, "Q2" = 2, "Q3" = 2, "Q4" = 2, "FY Total" = 2),bold=TRUE) %>%
  add_header_above(c("",title.array),bold = T) %>%
  row_spec(0:0, bold = T, color = "white", background = bkcolor)
  return(tmp)
}


####HQ####
rownames(df.hq) <- recodeEvents(df.hq$Event.or.distribution.type.)
df.hq <- df.hq %>%
  select(-Event.or.distribution.type.)
makePretty(df = df.hq,site.name = "Headquarters",bkcolor = "cyan")

# kable(df.hq,format = "latex",col.names = c(rep(c("Metrics","Actual"),5))) %>% 
#   kable_styling(latex_options = "striped", full_width = F, font_size = 8) %>%
#   column_spec(0:1, bold = T,width="6cm") %>%
#   column_spec(2:10,width="1cm") %>%
#   add_header_above(c("Outreach Event or Distribution ", "Q1" = 2, "Q2" = 2, "Q3" = 2, "Q4" = 2, "FY Total" = 2)) %>%
#   add_header_above(c("", "Headquarters" = 10),bold = T) %>%
#   row_spec(0:0, bold = T, color = "white", background = "blue")


####PB####
rownames(df.pb) <- recodeEvents(df.pb$Event.or.distribution.type.)
df.pb <- df.pb %>% 
  select(-Event.or.distribution.type.)
makePretty(df = df.pb,site.name = "Pueblo",bkcolor = "JungleGreen")

# kable(df.pb,format = "latex",col.names = c(rep(c("Metrics","Actual"),5))) %>% 
#   kable_styling(latex_options = "striped", full_width = F, font_size = 8) %>%
#   column_spec(0:1, bold = T,width="8cm") %>%
#   row_spec(0:0, bold = T, color = "white", background = "green") %>%
#   add_header_above(c("Outreach Event or Distribution ", "Q1" = 2, "Q2" = 2, "Q3" = 2, "Q4" = 2, "FY Total" = 2)) %>%
#   add_header_above(c("", "Pueblo" = 10))


####BG####
rownames(df.bg) <- recodeEvents(df.bg$Event.or.distribution.type.)
df.bg <- df.bg %>%
  select(-Event.or.distribution.type.)
makePretty(df=df.bg, site.name = "Blue Grass", bkcolor = "Plum")

# kable(df.bg, "latex",col.names = c(rep(c("Metrics","Actual"),5))) %>% 
#   kable_styling(latex_options = "striped", full_width = F, font_size = 8) %>%
#   column_spec(0:1, bold = T,width="8cm") %>%
#   row_spec(0:0, bold = T, color = "white", background = "red") %>%
#   add_header_above(c("Outreach Event or Distribution ", "Q1" = 2, "Q2" = 2, "Q3" = 2, "Q4" = 2, "FY Total" = 2)) %>%
#   add_header_above(c("", "Blue Grass" = 10))


####FEEDBACK####
colnames(df.feedback) <- rep("",7)
kable(df.feedback, "latex") %>% 
  kable_styling(latex_options = "striped", full_width = F, font_size = 8) %>% 
  # row_spec(0:0, bold = T, color = "white", background = "Dandelion") %>%
  group_rows("",3,4) %>%
  group_rows("",5,6) %>% 
  column_spec(0:1, bold = T) %>%
  add_header_above(c("FEEDBACK SNAPSHOT" = 2, "Q1" = 1, "Q2" = 1, "Q3" = 1, "Q4" = 1, "FYTD" = 1),bold=TRUE) %>%
  row_spec(0:0, bold = T, color = "white", background = "Dandelion")

```

